'use client';
import { useEffect, useState } from 'react';
import { ApiError } from '@/services/api';
import { type AdminScheme, listSchemes, reindexScheme, updateSchemeStatus } from '@/services/schemes';

export default function SchemesPage() {
  const [items, setItems] = useState<AdminScheme[]>([]); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [search, setSearch] = useState(''); const [status, setStatus] = useState<AdminScheme['status'] | ''>(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [refresh, setRefresh] = useState(0);
  useEffect(() => { let active = true; listSchemes({ page, search, status: status || undefined }).then((result) => { if (active) { setItems(result.items); setTotalPages(Math.max(1, result.totalPages)); } }).catch((cause) => { if (active) setError(cause instanceof ApiError ? cause.message : 'Unable to load schemes.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [page, search, status, refresh]);
  const reload = () => { setLoading(true); setRefresh((value) => value + 1); };
  async function setSchemeStatus(scheme: AdminScheme, next: AdminScheme['status']) { if (next === scheme.status || !window.confirm(`Set ${scheme.name} to ${next}?`)) return; try { await updateSchemeStatus(scheme.id, next); reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Action failed.'); } }
  async function index(scheme: AdminScheme) { if (!window.confirm(`Re-index ${scheme.name}?`)) return; try { await reindexScheme(scheme.id); reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Indexing failed.'); } }
  return <section className="space-y-4"><div><h2 className="text-xl font-bold">Government schemes</h2><p className="text-sm text-slate-600">Scraped data and administrative status are shown separately.</p></div><div className="flex gap-3"><input value={search} onChange={(e) => { setPage(1); setSearch(e.target.value); }} placeholder="Search schemes" className="rounded border p-2" /><select value={status} onChange={(e) => { setPage(1); setStatus(e.target.value as AdminScheme['status'] | ''); }} className="rounded border p-2"><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="DISABLED">Disabled</option><option value="ARCHIVED">Archived</option></select></div>{error && <p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}{loading ? <p>Loading schemes…</p> : <div className="overflow-x-auto rounded border bg-white"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Scheme</th><th>Source</th><th>Status</th><th>Indexed</th><th className="p-3">Actions</th></tr></thead><tbody>{items.map((scheme) => <tr key={scheme.id} className="border-b"><td className="p-3"><div className="font-medium">{scheme.name}</div><div className="text-slate-500">{scheme.category || 'Uncategorised'} · {scheme.state || 'All India'} · {scheme.origin === 'SCRAPED' ? 'Scraped data' : 'Admin-modified'}</div></td><td>{scheme.sourceUrl ? <a className="text-blue-700 underline" href={scheme.sourceUrl} target="_blank" rel="noreferrer">View source</a> : 'Not recorded'}</td><td><select value={scheme.status} onChange={(e) => setSchemeStatus(scheme, e.target.value as AdminScheme['status'])} className="rounded border p-1"><option value="ACTIVE">Active</option><option value="DISABLED">Disabled</option><option value="ARCHIVED">Archived</option></select></td><td>{scheme.indexedAt ? new Date(scheme.indexedAt).toLocaleString() : 'Not indexed'}</td><td className="p-3"><button disabled={scheme.status !== 'ACTIVE'} onClick={() => index(scheme)} className="rounded border px-2 py-1 disabled:opacity-50">Re-index</button></td></tr>)}</tbody></table>{items.length === 0 && <p className="p-4 text-slate-600">No schemes match the current filters.</p>}</div>}<div className="flex gap-3"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded border px-3 py-1 disabled:opacity-50">Previous</button><span>Page {page} of {totalPages}</span><button disabled={page >= totalPages} onClick={() => setPage(page + 1)} className="rounded border px-3 py-1 disabled:opacity-50">Next</button></div></section>;
}
