import React, { useState } from 'react';
import { ActiveTab } from '../types';
import { Shield, Lock, FileWarning, HelpCircle, ChevronDown, CheckCircle2 } from 'lucide-react';

interface LegalCenterProps {
  setActiveTab: (tab: ActiveTab) => void;
}

export const LegalCenter: React.FC<LegalCenterProps> = ({ setActiveTab }) => {
  const [openSection, setOpenSection] = useState<string>('privacy');

  const sections = [
    {
      id: 'privacy',
      title: 'Data & Privacy Policy',
      icon: Shield,
      status: 'Updated',
      statusColor: 'emerald',
      content: `SathiX OS operates on a strict Privacy-First model. 
      • We do not store your Aadhaar biometrics or OTPs. 
      • Document intelligence runs securely and temporarily in memory during sessions.
      • Voice inputs are processed anonymously for intent recognition only.
      • We comply with the Digital Personal Data Protection Act, 2023 guidelines.`
    },
    {
      id: 'terms',
      title: 'Terms of Service',
      icon: FileWarning,
      status: 'Standard',
      statusColor: 'slate',
      content: `By using SathiX OS, you agree that this platform is a conversational interface to public government schemes. 
      SathiX OS acts as a facilitator and does not guarantee the final approval of any scheme or loan, which remains at the discretion of the respective nodal departments.`
    },
    {
      id: 'ai-safety',
      title: 'AI Transparency & Safety',
      icon: HelpCircle,
      status: 'Important',
      statusColor: 'blue',
      content: `All recommendations generated by the SathiX AI are based on the latest available Ministry guidelines. 
      However, AI can occasionally hallucinate. We strongly recommend verifying critical deadlines and required documents on official government websites (india.gov.in) before final submission.`
    },
    {
      id: 'security',
      title: 'Security Certifications',
      icon: Lock,
      status: 'Verified',
      statusColor: 'emerald',
      content: `Data transmission is encrypted via TLS 1.3. User session data is tokenized and wiped post-session. SathiX OS architecture is designed to support CERT-In compliance standards.`
    }
  ];

  return (
    <div className="min-h-[calc(100vh-4rem)] bg-slate-50 text-slate-900 py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 w-full space-y-10">
        
        {/* Prototype Warning Banner */}
        <div className="p-4 rounded-2xl bg-amber-50 border border-amber-200 flex gap-4 items-start shadow-sm">
          <FileWarning className="w-6 h-6 text-amber-600 flex-shrink-0 mt-0.5" />
          <div>
            <h3 className="text-amber-800 font-bold text-sm">PROTOTYPE DISCLAIMER</h3>
            <p className="text-amber-700 text-xs mt-1 leading-relaxed font-medium">
              SathiX OS is a prototype concept designed for hackathon purposes. It is NOT an official portal of the Government of India. The legal content below is mocked for demonstration. Do not enter real sensitive personal information (like actual Aadhaar numbers) into this prototype.
            </p>
          </div>
        </div>

        <div className="text-center space-y-4">
          <h1 className="text-3xl font-black text-slate-900">Trust & Legal Center</h1>
          <p className="text-slate-600 text-sm font-medium">Transparency in how we handle your digital identity.</p>
        </div>

        <div className="space-y-4">
          {sections.map((sec) => {
            const Icon = sec.icon;
            const isOpen = openSection === sec.id;
            
            return (
              <div 
                key={sec.id}
                className={`border rounded-2xl transition-all duration-300 overflow-hidden ${
                  isOpen ? 'bg-white border-blue-300 shadow-sm' : 'bg-white border-slate-200 hover:border-slate-300 shadow-sm'
                }`}
              >
                <button
                  onClick={() => setOpenSection(isOpen ? '' : sec.id)}
                  className="w-full px-6 py-5 flex items-center justify-between focus:outline-none"
                >
                  <div className="flex items-center gap-4">
                    <div className={`p-2 rounded-xl ${isOpen ? 'bg-blue-50 text-blue-600' : 'bg-slate-50 text-slate-500 border border-slate-100'}`}>
                      <Icon className="w-5 h-5" />
                    </div>
                    <div className="text-left">
                      <h3 className="font-bold text-sm text-slate-900">{sec.title}</h3>
                    </div>
                  </div>
                  <div className="flex items-center gap-4">
                    <span className={`hidden sm:inline-block px-2.5 py-0.5 rounded text-[10px] font-bold border ${
                      sec.statusColor === 'emerald' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' :
                      sec.statusColor === 'blue' ? 'bg-blue-50 text-blue-700 border-blue-200' :
                      'bg-slate-50 text-slate-600 border-slate-200'
                    }`}>
                      {sec.status}
                    </span>
                    <ChevronDown className={`w-5 h-5 transition-transform duration-300 ${isOpen ? 'rotate-180 text-blue-600' : 'text-slate-400'}`} />
                  </div>
                </button>
                
                {isOpen && (
                  <div className="px-6 pb-6 pt-2 text-sm text-slate-700 leading-relaxed border-t border-slate-100 mt-2 font-medium">
                    <div className="pt-4 whitespace-pre-line">
                      {sec.content}
                    </div>
                    {sec.statusColor === 'emerald' && (
                      <div className="mt-4 flex items-center gap-2 text-xs text-emerald-700 font-bold bg-emerald-50 p-2 rounded-lg border border-emerald-200 inline-flex">
                        <CheckCircle2 className="w-4 h-4 text-emerald-600" /> End-to-End Encrypted
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>

      </div>
    </div>
  );
};
