'use client';
import { FormEvent, useEffect, useState } from 'react';
import { ApiError } from '@/services/api';
import { cancelScraperJob, createScraperJob, getScraperStatus, listScraperJobs, retryScraperJob, type ScraperJob, type ScraperStatus } from '@/services/scraper';

export default function ScraperPage() {
  const [jobs, setJobs] = useState<ScraperJob[]>([]); const [summary, setSummary] = useState<ScraperStatus | null>(null); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [sourceUrl, setSourceUrl] = useState(''); const [sourceName, setSourceName] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [refresh, setRefresh] = useState(0);
  useEffect(() => { let active = true; Promise.all([getScraperStatus(), listScraperJobs(page)]).then(([status, result]) => { if (active) { setSummary(status); setJobs(result.items); setTotalPages(Math.max(1, result.totalPages)); } }).catch((cause) => { if (active) setError(cause instanceof ApiError ? cause.message : 'Unable to load scraper jobs.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [page, refresh]);
  const reload = () => { setLoading(true); setRefresh((value) => value + 1); };
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); try { await createScraperJob(sourceUrl, sourceName || undefined); setSourceUrl(''); setSourceName(''); reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to queue scraper job.'); } }
  async function retry(job: ScraperJob) { if (!window.confirm(`Retry ${job.sourceName || job.sourceUrl}?`)) return; try { await retryScraperJob(job.id); reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Retry failed.'); } }
  async function cancel(job: ScraperJob) { if (!window.confirm(`Cancel ${job.sourceName || job.sourceUrl}?`)) return; try { await cancelScraperJob(job.id); reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'This job cannot be cancelled.'); } }
  return <section className="space-y-5"><div><h2 className="text-xl font-bold">Scraper management</h2><p className="text-sm text-slate-600">Jobs are queued through Backend and shown from persisted worker status.</p></div><form onSubmit={submit} className="flex flex-wrap gap-3 rounded border bg-white p-4"><input required type="url" value={sourceUrl} onChange={(e) => setSourceUrl(e.target.value)} placeholder="https://government.example/schemes" className="min-w-64 rounded border p-2" /><input value={sourceName} onChange={(e) => setSourceName(e.target.value)} placeholder="Source name (optional)" className="rounded border p-2" /><button className="rounded bg-emerald-700 px-4 py-2 text-white">Queue scraper</button></form>{summary && <div className="grid gap-3 sm:grid-cols-3"><div className="rounded border bg-white p-3">Queued: {summary.byStatus.QUEUED || 0}</div><div className="rounded border bg-white p-3">Running: {summary.byStatus.RUNNING || 0}</div><div className="rounded border bg-white p-3">Failed: {summary.byStatus.FAILED || 0}</div></div>}{error && <p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}{loading ? <p>Loading jobs…</p> : <div className="overflow-x-auto rounded border bg-white"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Source</th><th>Status</th><th>Progress</th><th>Error</th><th className="p-3">Actions</th></tr></thead><tbody>{jobs.map((job) => <tr key={job.id} className="border-b"><td className="p-3"><div className="font-medium">{job.sourceName || 'Unnamed source'}</div><a className="text-xs text-blue-700 underline" href={job.sourceUrl} target="_blank" rel="noreferrer">{job.sourceUrl}</a></td><td>{job.status}</td><td>{job.pagesProcessed} pages · {job.schemesDiscovered} discovered · {job.failedItems} failed items</td><td className="max-w-64 truncate text-red-700">{job.error || '—'}</td><td className="space-x-2 p-3">{['FAILED', 'CANCELLED'].includes(job.status) && <button onClick={() => retry(job)} className="rounded border px-2 py-1">Retry</button>}{job.status === 'QUEUED' && <button onClick={() => cancel(job)} className="rounded border px-2 py-1">Cancel</button>}</td></tr>)}</tbody></table>{jobs.length === 0 && <p className="p-4 text-slate-600">No scraper jobs have been recorded.</p>}</div>}<div className="flex gap-3"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded border px-3 py-1 disabled:opacity-50">Previous</button><span>Page {page} of {totalPages}</span><button disabled={page >= totalPages} onClick={() => setPage(page + 1)} className="rounded border px-3 py-1 disabled:opacity-50">Next</button></div></section>;
}
